name: 'Merge Check'
description: 'Validate merge direction'
inputs:
  ACCEPTABLE_MERGES:
    description: 'A list of acceptable merges'
    required: true
runs:
  using: "composite"
  steps:
    - name: Validate Merge Direction
      shell: bash
      run: |
        echo "PR merging from: ${{ github.head_ref }}"
        echo "PR merging to: ${{ github.base_ref }}"
        echo "Possible Merges:"
        
        ACCEPTABLE=false
        MERGE_OPTIONS="${{ inputs.ACCEPTABLE_MERGES }}"
        # for MERGE_OPTION in $MERGE_OPTIONS
        while IFS= read -r MERGE_OPTION
        do
          echo "  $MERGE_OPTION"
          FROM_BRANCH=$(echo MERGE_OPTION | cut -f 1 -d " ")
          TO_BRANCH=$(echo MERGE_OPTION | rev | cut -f 1 -d " " | rev)
          if [[ "${{github.head_ref}}" == $FROM_BRANCH ]] && \
             [[ "${{github.base_ref}}" == $TO_BRANCH ]]
          then
            ACCEPTABLE=true
          fi
        done <<< "$MERGE_OPTIONS"
        
        if [[ $PASS == "true" ]]
        then
          echo "You're okay to merge!"
        else
          echo "::error ::You cannot merge branch '${{github.head_ref}}' to branch '${{github.base_ref}}'."
          echo "::error ::Possible merges are: $MERGE_OPTIONS"
          exit 1;
        fi
